### ISSUE TITLE
Starbound 1.0+ update

### ISSUE THREAD

**Issue by LoPhatKao** [Cratesmith/VesselBound#2]
hey man, if you're not going to update and post this mod, may i?
admittedly I haven't used or looked at it in a while, but still have it on my pleased giraffe install.
from what i recall, still the best item storage management system for sb i've seen

(sorry about opening an issue, can't seem to find a way to pm)

**Comment by Cratesmith** [comment]
Hey there. I don't have much time to work on it at the moment but our team
is getting back into Starbound so I am looking at updating it.

If you want to help get it up and running again please send pull requests
for your updates.

On another note the project is MIT licence so you already can do whatever
you want with it

**Comment by LoPhatKao** [comment]
cool, will see what i can do when i have some time off work
didn't know about the licence, but still would've been bad form to not ask first :)

**Comment by Cratesmith** [comment]
If you were interested in helping out, I've started a new branch for the starbound 1.0 update and got it "running" (filters are non fuctional but sinks/inboxes work)
